### ISSUE TITLE
Sub directory and Routing

### ISSUE THREAD

**Issue by kfwebdev** [ryelle/Anadama-React#3]
After setting up I wasn't seeing any posts on the homepage. Turns out it was because my local WordPress instance was in a sub directory of the domain (ie: localhost/mysite/). The back button also wants to go back to / as well instead of the site root /mysite/.

**Comment by kfwebdev** [comment]
Looks like there is a page.base() function in the page router. That looks like what I should be using.

**Comment by nolaandy** [comment]
I'm having a similar issue.
I edited js/index.jsx to reflect the directory my wamp site was in:

```
// page.base( '/' );
page( '/nameOfWampFolder',           Controller.setup, Controller.navigation, Controller.posts );
```

I see that app.js has been updated after making this change.

When I visit a post though it appears to be the original post created. If I edit a post, the changes are not shown. I have verified the data has been updated via phpMyAdmin.

Also, the back button still goes to localhost instead of localhost/nameOfWampFolder

Is there something I'm missing? Any help would be greatly appreciated! Thank you.

**Comment by ryelle** [comment]
@nolaandy I've pushed an update which pulls the base path out of WordPress, so all the routes should work in sub-directory installs now. Can you let me know if this also fixes the back-button issue?

**Comment by ryelle** [comment]
> When I visit a post though it appears to be the original post created. If I edit a post, the changes are not shown. I have verified the data has been updated via phpMyAdmin.

This is due to the overly-aggressive caching. If you run `localStorage.clear();` in the console of your browser, it'll clear all the API responses the theme has cached, and your post should be updated.

EDIT: The caching definitely needs some fine-tuning, if you have any ideas, please [open a new issue](https://github.com/ryelle/Anadama-React/issues/new). Thanks!
